SELECT b.BRANCH_NAME, a.CITY AS location, ROUND(AVG(t.TRANSACTION_TOTAL_AMOUNT)) AS avg_transaction_value
FROM BRANCH b
JOIN ADDRESS a ON b.ADDRESS_ID = a.ADDRESS_ID  -- Join with ADDRESS table on ADDRESS_ID
JOIN TRANSACTIONS t ON b.BRANCH_ID = t.BRANCH_ID
GROUP BY b.BRANCH_NAME, a.CITY;