SELECT b.BRANCH_NAME, mi.MENU_ITEM_NAME, SUM(ct.MENU_ITEM_AMOUNT) AS total_coffee_sold
FROM BRANCH b
JOIN ADDRESS a ON b.ADDRESS_ID = a.ADDRESS_ID
JOIN TRANSACTIONS t ON b.BRANCH_ID = t.BRANCH_ID
JOIN CAFE_TRANSACTION ct ON t.TRANSACTION_ID = ct.TRANSACTION_ID
JOIN MENU_ITEM mi ON ct.MENU_ITEM_ID = mi.MENU_ITEM_ID
WHERE mi.MENU_ITEM_NAME LIKE '%Latte%'
GROUP BY b.BRANCH_NAME, mi.MENU_ITEM_NAME
ORDER BY b.BRANCH_NAME, total_coffee_sold DESC;