SELECT b.BRANCH_NAME, a.CITY AS location, EXTRACT(MONTH FROM t.TRANSACTION_DATE) AS transaction_month,
       SUM(t.TRANSACTION_TOTAL_AMOUNT) AS monthly_revenue
FROM BRANCH b
JOIN ADDRESS a ON b.ADDRESS_ID = a.ADDRESS_ID  -- Join with ADDRESS table
JOIN TRANSACTIONS t ON b.BRANCH_ID = t.BRANCH_ID
GROUP BY b.BRANCH_NAME, a.CITY, EXTRACT(MONTH FROM t.TRANSACTION_DATE)
ORDER BY b.BRANCH_NAME, transaction_month;