SELECT 'CoWork' AS Transaction_Type, ROUND(AVG(T1.TRANSACTION_TOTAL_AMOUNT),2) AS Average_Transaction
FROM TRANSACTIONS t1
LEFT JOIN COWORK_TRANSACTION cwt ON cwt.TRANSACTION_ID = t1.TRANSACTION_ID
UNION ALL
SELECT 'Event' AS Transaction_Type, round(AVG(T2.TRANSACTION_TOTAL_AMOUNT),2) AS Average_Transaction
FROM TRANSACTIONS t2
LEFT JOIN EVENT_TRANSACTION et ON et.TRANSACTION_ID = t2.TRANSACTION_ID
UNION ALL
SELECT 'Cafe' AS Transaction_Type, round(AVG(T3.TRANSACTION_TOTAL_AMOUNT),2) AS Average_Transaction
FROM TRANSACTIONS t3
LEFT JOIN CAFE_TRANSACTION ct ON ct.transaction_id = t3.transaction_id;
