-- STOCK
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (1,'Cups (L)', 200,2.00,'Large cups', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (2,'Cups (M)', 150,1.50,'Medium cups', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (3,'Cups (S)', 100,1.00,'Small cups', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (4,'Lids', 300,0.50,'Lids for cups', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (5,'Lids', 250,0.50,'Lids for cups', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (6,'Lids', 200,0.50,'Lids for cups', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (7,'Coffee Beans (Premium Blend)', 50,100.00,'Premium blend', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (8,'Coffee Beans (Regular Blend)', 40,90.00,'Regular blend', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (9,'Coffee Beans (Decaf Blend)', 30,80.00,'Decaf blend', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (10,'Coffee Beans (Premium Blend)', 50,100.00,'Premium blend', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (11,'Coffee Beans (Regular Blend)', 40,90.00,'Regular blend', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (12,'Coffee Beans (Decaf Blend)', 30,80.00,'Decaf blend', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (13,'Coffee Beans (Premium Blend)', 50,100.00,'Premium blend', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (14,'Coffee Beans (Regular Blend)', 40,90.00,'Regular blend', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (15,'Coffee Beans (Decaf Blend)', 30,80.00,'Decaf blend', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (16,'Cups (M)', 150,1.50,'Medium cups', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (17,'Cups (S)', 100,1.00,'Small cups', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (18,'Cups (L)', 200,2.00,'Large cups', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (19,'Cups (S)', 150,1.50,'Medium cups', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (20,'Cups (L)', 250,2.50,'Large cups', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (21,'Cups (M)', 180,2.00,'Medium cups', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (22,'Chicken Mayo and Bacon Wrap', 50,55.00,'Delicious wrap with chicken mayo and bacon', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (23,'Chicken Mayo and Bacon Wrap', 50,55.00,'Delicious wrap with chicken mayo and bacon', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (24,'Chicken Mayo and Bacon Wrap', 50,55.00,'Delicious wrap with chicken mayo and bacon', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (25,'Honey-and-Soy-Glazed Chicken Wrap', 40,60.00,'Tasty wrap with honey and soy-glazed chicken', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (26,'Honey-and-Soy-Glazed Chicken Wrap', 40,60.00,'Tasty wrap with honey and soy-glazed chicken', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (27,'Honey-and-Soy-Glazed Chicken Wrap', 40,60.00,'Tasty wrap with honey and soy-glazed chicken', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (28,'Beef and Caramelised Onion Wrap', 35,65.00,'Savory wrap with beef and caramelised onions', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (29,'Beef and Caramelised Onion Wrap', 35,65.00,'Savory wrap with beef and caramelised onions', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (30,'Beef and Caramelised Onion Wrap', 35,65.00,'Savory wrap with beef and caramelised onions', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (31,'Chicken and Bacon Salad', 45,75.00,'Fresh salad with chicken and bacon', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (32,'Chicken and Bacon Salad', 45,75.00,'Fresh salad with chicken and bacon', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (33,'Chicken and Bacon Salad', 45,75.00,'Fresh salad with chicken and bacon', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (34,'Grilled Chicken Stack', 30,85.00,'Stack of grilled chicken and veggies', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (35,'Grilled Chicken Stack', 30,85.00,'Stack of grilled chicken and veggies', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (36,'Grilled Chicken Stack', 30,85.00,'Stack of grilled chicken and veggies', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (37,'Quiche', 25,45.00,'Delicious quiche', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (38,'Quiche', 25,45.00,'Delicious quiche', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (39,'Quiche', 25,45.00,'Delicious quiche', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (43,'Chocolate Powder', 80,25.00,'Delicious chocolate powder for beverages', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (44,'Chocolate Powder', 80,25.00,'Delicious chocolate powder for beverages', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (45,'Chocolate Powder', 80,25.00,'Delicious chocolate powder for beverages', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (46,'Chai Powder', 60,20.00,'Warm and aromatic chai powder', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (47,'Chai Powder', 60,20.00,'Warm and aromatic chai powder', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (48,'Chai Powder', 60,20.00,'Warm and aromatic chai powder', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (49,'Ice', 200,5.00,'Refreshing ice cubes', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (50,'Ice', 200,5.00,'Refreshing ice cubes', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (51,'Ice', 200,5.00,'Refreshing ice cubes', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (52,'Iced Cups', 150,3.00,'Cups for iced beverages', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (53,'Iced Cups', 150,3.00,'Cups for iced beverages', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (54,'Iced Cups', 150,3.00,'Cups for iced beverages', 3);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (55, 'Milk', 50, 11, 'Fresh farm milk', 1);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (56, 'Milk', 50, 11, 'Fresh farm milk', 2);
INSERT INTO STOCK(stock_id, stock_name, stock_amount, STOCK_PURCHASE_PRICE_PER_ITEM, STOCK_DESCRIPTION, branch_id) VALUES (57, 'Milk', 50, 11, 'Fresh farm milk', 3);