-- ===== Latte =====
-- 1
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,7,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,8,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,9,1,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,7,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,8,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,9,2,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,7,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,8,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,9,3,2.5);

-- 2
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,10,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,11,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,12,1,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,10,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,11,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,12,2,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,10,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,11,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,12,3,2.5);

-- 3
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,13,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,14,1,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,15,1,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,13,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,14,2,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,15,2,2.5);

INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,13,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,14,3,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,15,3,2.5);

-- ===== Mocha =====
-- 1
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,43,4,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,44,5,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,45,6,2.5);

-- 2
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,43,4,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,44,5,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,45,6,2.5);

-- 3
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,43,4,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,44,5,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,45,6,2.5);

-- ===== Chai Latte =====
-- 1
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,46,10,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,47,11,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,48,12,2.5);

-- 2
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,46,10,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,47,11,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,48,12,2.5);

-- 3
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,46,10,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,47,11,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,48,12,2.5);

-- ===== Iced Brewed Coffee =====
-- 1
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,49,13,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,50,14,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,51,15,2.5);

-- 2
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,49,13,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,50,14,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,51,15,2.5);

-- 3
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,49,13,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,50,14,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,51,15,2.5);

-- ===== Rooibos Tea =====
-- 1
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,55,16,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,56,17,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(1,57,18,2.5);

-- 2
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,55,16,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,56,17,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(2,57,18,2.5);

-- 3
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,55,16,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,56,17,2.5);
INSERT INTO PRODUCTION(EQUIPMENT_ID, STOCK_ID, MENU_ITEM_ID,PRODUCTION_ESTIMATED_TIME) VALUES(3,57,18,2.5);


